from __future__ import annotations

from pathlib import Path

from openpyxl import Workbook

from core.csv_parser import parse_csv
from core.table_parser import HeaderMode, ImportOptions, inspect_table, parse_table


def test_headerless_csv_preserves_first_row_and_assigns_column_names(tmp_path: Path) -> None:
    path = tmp_path / "headerless.csv"
    path.write_text("1,alpha,3\n2,beta,4\n", encoding="utf-8")

    result = parse_table(path, ImportOptions(header_mode=HeaderMode.NONE))

    assert list(result.dataframe.columns) == ["Column 1", "Column 2", "Column 3"]
    assert result.dataframe.astype(object).where(result.dataframe.notna(), None).values.tolist() == [
        [1, "alpha", 3],
        [2, "beta", 4],
    ]


def test_csv_normalizes_blank_and_duplicate_headers_without_dropping_columns(
    tmp_path: Path,
) -> None:
    path = tmp_path / "duplicates.csv"
    path.write_text("Force,,Force\n1,text,2\n", encoding="utf-8")

    result = parse_table(path, ImportOptions(header_mode=HeaderMode.FIRST_ROW))

    assert list(result.dataframe.columns) == ["Force", "Column 2", "Force (2)"]
    assert result.dataframe.iloc[0].tolist() == [1, "text", 2]


def test_mixed_and_empty_columns_are_preserved(tmp_path: Path) -> None:
    path = tmp_path / "mixed.csv"
    path.write_text("number,text,empty\n1,a,\n2,b,\n", encoding="utf-8")

    result = parse_table(path)

    assert list(result.dataframe.columns) == ["number", "text", "empty"]
    assert result.column_types == {
        "number": "numeric",
        "text": "text",
        "empty": "empty",
    }


def test_xlsx_inspection_lists_sheets_and_suggests_first_non_empty(
    tmp_path: Path,
) -> None:
    path = tmp_path / "book.xlsx"
    workbook = Workbook()
    empty = workbook.active
    empty.title = "Empty"
    data = workbook.create_sheet("Measurements")
    data.append(["time", "value"])
    data.append([0, 10])
    workbook.create_sheet("Later").append(["other"])
    workbook.save(path)

    inspection = inspect_table(path)

    assert [(sheet.name, sheet.empty) for sheet in inspection.sheets] == [
        ("Empty", True),
        ("Measurements", False),
        ("Later", False),
    ]
    assert inspection.suggested_sheet == "Measurements"


def test_xlsx_selected_sheet_and_explicit_header_row_are_respected(
    tmp_path: Path,
) -> None:
    path = tmp_path / "book.xlsx"
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "Data"
    sheet.append(["Generated by instrument"])
    sheet.append(["Time", "Reading"])
    sheet.append([0, 4.5])
    workbook.save(path)

    result = parse_table(
        path,
        ImportOptions(sheet="Data", header_mode=HeaderMode.ROW, header_row=2),
    )

    assert list(result.dataframe.columns) == ["Time", "Reading"]
    assert result.dataframe.values.tolist() == [[0, 4.5]]
    assert result.header_row == 1


def test_parse_csv_compatibility_api_uses_generic_result(tmp_path: Path) -> None:
    path = tmp_path / "compatible.csv"
    path.write_text("name,value\nalpha,1\n", encoding="utf-8")

    result = parse_csv(path)

    assert result.column_types == {"name": "text", "value": "numeric"}
